### ISSUE TITLE
brew repo has migrated

### ISSUE THREAD

**Issue by tseemann** [bcgsc/ntCard#10]
OLD
brew install homebrew/science/ntcard

NEW
brew install brewsci/bio/ntcard

**Comment by sjackman** [comment]
Migration PR https://github.com/brewsci/homebrew-bio/pull/78

**Comment by sjackman** [comment]
Fixed by b279d53bc5ddafa3b662ed5c8f966e7e43dc6803

**Comment by mohamadi** [comment]
Thanks @tseemann and @sjackman
