### ISSUE TITLE
headerless fasta sequences seem to be ignored

### ISSUE THREAD

**Issue by rsharris** [bcgsc/ntCard#12]
(Using the tagged release 1.0.1)

FYI, it seems that if given a fasta file that has no ">" header, ntcard simply ignores the whole file.

In my case, it was obvious there was *some* problem, because I only had one file, and since it had no header, I got what were obviously meaningless results (a few zeros followed by a bunch of 2^63s).  But it did take me some time to figure out what I was doing wrong.

Seems like the user ought to made aware of this, either a note in the readme, or a runtime warning if a headerless sequence is encountered.

It seems possible that the underlying problem might ignore some of the input but not all, in which case the user would probably be unaware of it.

In case it makes any difference, I was piping my fasta in on stdin, and using /dev/stdin as the filename.

**Comment by sjackman** [comment]
ntCard ought to print an error when it encounters a FASTA/FASTQ file without a header.

**Comment by mohamadi** [comment]
@rsharris Thanks Bob for reporting this. I just added the fix to print an error when it encounters a FASTA/FASTQ file without a header.

**Comment by rsharris** [comment]
kewl

**Comment by sjackman** [comment]
Fixed by e3feb96a2dcc4272106a37b2f930d8c1417126d5
