### ISSUE TITLE
Tag a new stable release

### ISSUE THREAD

**Issue by sjackman** [bcgsc/ntCard#13]
Could you please tag a new stable release that includes the feature `
Added option for output to a single file`?

**Comment by sjackman** [comment]
I'd suggest version 2.0.0

**Comment by mohamadi** [comment]
Thanks @sjackman. Just made a new release for this feature.

**Comment by sjackman** [comment]
Thanks, Hamid! I'll update Bioconda and Homebrew.

**Comment by sjackman** [comment]
🍺 https://github.com/brewsci/homebrew-bio/pull/489
🐍 https://github.com/bioconda/bioconda-recipes/pull/11338
