### ISSUE TITLE
Show help when no parameters?

### ISSUE THREAD

**Issue by tseemann** [bcgsc/ntCard#16]
```
% ntcard

ntcard: missing arguments
ntcard: missing argument -k ...
Try `ntcard --help' for more information.
```

It would be nicer to just show the `--help` if there are ZERO arguments?
it usually means someone is trying to see how to run it.

**Comment by sjackman** [comment]
I actually disagree with this one. I prefer that running `foo` outputs this error message with exit status 1, like the GNU tools do.

**Comment by tseemann** [comment]
I mean still show the help - but exit code 1 and to STDERR (instead of 0 and stdout).

But your call :)

**Comment by sjackman** [comment]
Your case is a bit different, but it bugs me when tools output the error message, and then the complete output of `--help`, which buries the important error message in 30 lines of output.

**Comment by tseemann** [comment]
i only wanted the help if NO ARGS were provided whatsoever.  *i.e.* `argc=1`
