### ISSUE TITLE
Stop automatic outputting to "freq_kNN.hist"

### ISSUE THREAD

**Issue by tseemann** [bcgsc/ntCard#17]
I was shocked that `ntcard` ran with only a `-k` parameter and wrote a file to my folder. It took me a while to realise becuase i was in a folder with lots of sequence files.

Maybe the `-p` option should be mandatory and not have a default

The principle of "least surprise" is useful for command line tools.

P.S. I am a hypocrite, because some of my tools have default output folders :-P

**Comment by sjackman** [comment]
I agree that `-p` should not have a default value.
@tseemann Try the new `--out` file format! It outputs all the results to a single TSV file.

**Comment by tseemann** [comment]
Ok, i was testing on 1.0.0 but can see the new option now. Thanks.
