### ISSUE TITLE
Speed doesn't change when --threads increases?

### ISSUE THREAD

**Issue by tseemann** [bcgsc/ntCard#19]
This is on a FASTQ file with `Reads   1859724 Yield   274758053`

```
for N in $(seq 1 18); do echo threads=$N && ntcard -t $N -k 25 -p ntcard$N R1.fq.gz ; done
threads=1
Runtime(sec): 6.8182
threads=2
Runtime(sec): 6.7579
threads=3
Runtime(sec): 6.3849
threads=4
Runtime(sec): 6.4639
threads=5
Runtime(sec): 6.6152
threads=6
Runtime(sec): 6.5880
threads=7
Runtime(sec): 6.7932
threads=8
Runtime(sec): 6.6067
threads=9
Runtime(sec): 6.6375
threads=10
Runtime(sec): 6.5650
threads=11
Runtime(sec): 6.6318
threads=12
Runtime(sec): 6.3923
threads=13
Runtime(sec): 6.5634
threads=14
Runtime(sec): 6.6389
threads=15
Runtime(sec): 6.5851
threads=16
Runtime(sec): 6.5536
threads=17
Runtime(sec): 6.6643
threads=18
Runtime(sec): 6.7836
```

**Comment by tseemann** [comment]
I just upgraded to 1.1.0 and it seems to have gotten slower?

```
for N in $(seq 1 18); do echo threads=$N && ntcard -t $N -k 25 -p ntcard$N R1.fq.gz ; done
threads=1
Runtime(sec): 7.6703
threads=2
Runtime(sec): 7.7089
threads=3
Runtime(sec): 7.6456
threads=4
Runtime(sec): 7.6201
threads=5
Runtime(sec): 7.5373
threads=6
Runtime(sec): 7.5686
threads=7
Runtime(sec): 7.7034
threads=8
Runtime(sec): 7.5518
```

**Comment by sjackman** [comment]
The hash function has better hash properties now, and it may be slower. Hamid could elaborate.
Can you try a larger file that takes > 1 min to run, and see if it scales better?

**Comment by tseemann** [comment]
Any reason why `--threads` does nothing?
Does it only work if i pass multiple files or something? ie. it's input file parallel only

**Comment by tseemann** [comment]
So i tested in a single FASTA file with 3 Mbp of contigs. Very small compared to fastq.

```
% ntcard -k 25 -p 1 -o foo -p foo lepto.fna
25      F1      4592928
25      F0      4370987
Runtime(sec): 2.8704
```

It took way longer than expected.  This implies there is some expensive "setup" time going on in all these runs?

**Comment by mohamadi** [comment]
The ntCard parallelism is on files instead of reads. When input is a single file it will run in single-thread mode no matter what number of thread you set using -t.

**Comment by tseemann** [comment]
Ok that makes sense.  But why does a tiny FASTA take as long as a big FASTQ ?

**Comment by mohamadi** [comment]
```
[hmohamadi@hpcg01 ntCard]$ ~/ntCard/ntcard -k 25 ERR294494_5M.fq
Runtime(sec): 11.1952
[hmohamadi@hpcg01 ntCard]$ ~/ntCard/ntcard -k 25 ERR294494_5M.fa
Runtime(sec): 10.7901
[hmohamadi@hpcg01 ntCard]$
```

**Comment by tseemann** [comment]
Try running it on a small bacterial FASTA file. ie. only 3M kmers TOTAL in that. Still takes 4 seconds. Not sure why?

**Comment by mohamadi** [comment]
@tseemann due to the one-time setup cost for a fixed-size count table regardless of dataset cardinality.

**Comment by tseemann** [comment]
I realise also that the number of UNIQUE kmers is "similar" between an assembled genome and it's reads. The overhead of a new kmer >> overhead of incrementing existing kmer?

**Comment by mohamadi** [comment]
@tseemann, as @sjackman pointed out the runtime difference between ntcard-1.0.1 and ntcard-1.1.0 is due to the change in ntHash which is more accurate due to a change in the periodicity.

**Comment by sjackman** [comment]
It's just creating the data structure of the empty table of counts that takes ~3s (I gather, from what Hamid is saying).
