### ISSUE TITLE
problem with make

### ISSUE THREAD

**Issue by zjlahey** [bcgsc/ntCard#2]
Trying to _make_ and receive the following error:

```
g++ -Wall -O3 -fopenmp -Ilib -ldl -o ntcard ntcard.cpp lib/Uncompress.cpp lib/SignalHandler.cpp lib/Fcontrol.cpp
/usr/bin/ld: /tmp/cczwFT7G.o: undefined reference to symbol 'dlsym@@GLIBC_2.2.5'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libdl.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:12: recipe for target 'ntcard' failed
make: *** [ntcard] Error 1
```

Any help would be appreciated. Thank you!

**Comment by sjackman** [comment]
There's a bug in the Makefile. The `-l` options need to appear after the source file `ntcard.cpp`
```sh
g++ -Wall -O3 -fopenmp -o ntcard ntcard.cpp lib/Uncompress.cpp lib/SignalHandler.cpp lib/Fcontrol.cpp -Ilib -ldl
```

**Comment by sjackman** [comment]
You may want to try using Linuxbrew to install `ntcard`
See http://linuxbrew.sh then `brew install ntcard`

**Comment by zjlahey** [comment]
Thanks for you help, but I still can't get it to work. I installed linuxbrew and it doesn't recognize ntcard:

brew install homebrew/science/ntcard
Error: No available formula with the name "homebrew/science/ntcard" 
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
Error: No formulae found in taps.

I've also tried editing the make file to no avail.

**Comment by mohamadi** [comment]
I just pushed the AUTOTOOLS version to build ntCard. 
Please follow the instruction in README.md to build ntcard and let me know if it works.

**Comment by zjlahey** [comment]
It works, thanks!

**Comment by sjackman** [comment]
My mistake, `ntcard` wasn't yet in Homebrew, but it is now! Try once again
```
brew install homebrew/science/ntcard
```
