### ISSUE TITLE
Add -h alias for --help ?

### ISSUE THREAD

**Issue by tseemann** [bcgsc/ntCard#20]
I notice all the other parameters have short and long options but not help.

**Comment by sjackman** [comment]
I typically don't have short options for `--help` and `--version`. There's only 26 letters, so I save 'em for important options. =P

**Comment by tseemann** [comment]
You are evil if you use `-h` for something other than help.   
`grep` is one of the few tools that does this.

**Comment by tseemann** [comment]
Ok, you win Jackman. THIS TIME.

**Comment by sjackman** [comment]
![Spy vs Spy](https://betanews.com/wp-content/uploads/2017/03/Spy_vs_Spy.jpg)
