### ISSUE TITLE
ntcard file.gbk fails, but file.gff works?

### ISSUE THREAD

**Issue by tseemann** [bcgsc/ntCard#23]
Does `ntcard` support GFF files with embedded FASTA at the end?

```
% ntcard -k25 NC_000913.gbk
Error in reading file: NC_000913.gbk

% ntcard -k25 NC_000913.gff3
Runtime(sec): 3.1387
```

**Comment by mohamadi** [comment]
@tseemann ntCard only supports fastq, fasta, sam and bam formats. Do you think it would be useful to support GFF/GBK?

**Comment by sjackman** [comment]
I'd say that'd be overkill. FASTA/FASTQ is fine.

**Comment by sjackman** [comment]
It looks like it's not failing on the NC_000913.gff3 file though. It should give an error message and fail.

**Comment by mohamadi** [comment]
@tseemann @sjackman I addressed all the 7 open issues. Please let me know if you need more modifications. Thanks for your help.

**Comment by harish0201** [comment]
Hi!

Given that bams are being supported, does this mean I can pass PacBio Sequel's Bams to ntCard?
