### ISSUE TITLE
K-mers with odd frequency having 0 counts

### ISSUE THREAD

**Issue by TEcandidates** [bcgsc/ntCard#24]
Hi!

I've been using ntCard v1.1.0 with success until recently. The command I have used is the following:
`ntcard -p $outputbasename -t100 -k12,24,36,48,60,72,84,96,108,120,132 @$inputfile > $log`
where $outputbasename is a name generated based on the input file, stored in $inputfile, which has the list of files to be processed.

The result I have got in the last files I have processed using ntCard have odd frequencies with a 0, like this (first lines of a file, I have omitted F0 and F1):
```
1       0
2       1839217003
3       0
4       779118217
5       0
6       640700808
7       0
8       458220499
```
and this (last lines of the same file):
```
991     0
992     125
993     0
994     39
995     0
996     31
997     0
998     65
999     0
1000    19
```

The only difference between the two ntCard runs is that in the first one, I used uncompressed fastq files, and in the second one, every file is compressed in gz format.

**Comment by sjackman** [comment]
Is every value of *k* like this, or only some?

**Comment by mohamadi** [comment]
@TEcandidates what is in the `$inputfile` variable?

**Comment by TEcandidates** [comment]
> 
> 
> Is every value of _k_ like this, or only some?

Yes, every k in this run (from 12 to 132)

**Comment by sjackman** [comment]
Oh, I know the answer. You likely have accidentally duplicated each FASTQ file twice in your list of FASTQ files, causing k-mer counts to be doubled. Another good reason to run ntCard before assembly for QC!

Have you used GenomeScope? It works really well with ntCard. I use it before every assembly. http://qb.cshl.edu/genomescope/

**Comment by TEcandidates** [comment]
@sjackman yes, that was it. I wrote a small script to generate the full path of the files, since they were in different folders. Just checked it, and the instruction to print the filenames was twice.

Didn't new about GenomeScope, will check it out, as I've been working on the same stuff, but locally.

@mohamadi so sorry about opening this issue, and thanks for the instant support.

**Comment by sjackman** [comment]
Glad we sorted it out!

@mohamadi Does ntCard have an output format GenomeScope?

@TEcandidates Delete the F0 and F1 lines and replace the tabs with spaces to use the output of ntCard with GenomeScope.
```sh
sed '/F/d' ntcard.tsv | tr '\t' ' ' >ntcard.txt
```

**Comment by sjackman** [comment]
@mohamadi Does ntCard have an output format GenomeScope?

**Comment by mohamadi** [comment]
@sjackman I'll add the genomescope option to the output in next release.

**Comment by sjackman** [comment]
Alternatively you could include a littler helper script `ntcard-to-genomescope` that converts the ntcard format to the format needed by genomescope.
** ntcard-to-genomescope**
```sh
#!/bin/sh
set -eu -o pipefail
exec sed '/F/d' "$@" | tr '\t' ' '
```
