### ISSUE TITLE
Support Uracil nucleotides in input files

### ISSUE THREAD

**Issue by kmnip** [bcgsc/ntCard#25]
Currently, uracil nucleotides are ignored because only A,C,G,T's are supported.
'U's can simply be treated as 'T's in RNA-seq data.

**Comment by mohamadi** [comment]
Sure, will add ‘U’ in the table.

**Comment by mohamadi** [comment]
Feature added. Closing the issue.

**Comment by kmnip** [comment]
Thanks Hamid, that's great! But I didn't see the commit?

**Comment by mohamadi** [comment]
> Thanks Hamid, that's great! But I didn't see the commit?

Done!

**Comment by kmnip** [comment]
Thank you!
