### ISSUE TITLE
Reg: kmer dump generation

### ISSUE THREAD

**Issue by harish0201** [bcgsc/ntCard#26]
Hi!

I scoured through the readme and I might have probably missed it, but do we have a "dump" option of sorts like from either kmc tools or jellyfish?

For example consider the output from Jellyfish dump option (and it can also output in a fasta format with the count as a header)

`TATTGTCATTATTCATTTTTT	1`
`GTAATTTTTGTGCGACACGAA	1`
`GCGGGCGGTATCCAGTTCGTT	1`
`ATGTAGGCCCGGATGTTTGCC	1`
`CATACAACAAGCGACGAGCAT	1`

Here 1 is the count of the kmers encountered. Would it be possible to generate an output like this as well?

The current output can then be retrieved from this dump as well.

**Comment by sjackman** [comment]
I don't think that's possible with ntCard. Check out https://github.com/bcgsc/ntHits
cc @mohamadi
