### ISSUE TITLE
Support for U bases not working properly

### ISSUE THREAD

**Issue by kmnip** [bcgsc/ntCard#27]
I noticed that the histograms for U's are still different from those of T's for committ 2a48882.

I noticed that `seedTab` was updated, but `msTab33r` and `msTab31l` haven't been updated.

**Comment by kmnip** [comment]
I fixed it! :smile:
See committ d6f832b
The histograms for RNA-seq data with U's and T's are now identical.

**Comment by mohamadi** [comment]
@kmnip Nice! Thanks for catching this Ka Ming!
