### ISSUE TITLE
ntCard report interpretation

### ISSUE THREAD

**Issue by hidvegin** [bcgsc/ntCard#29]
I tried today the ntCard with this parameters: ntcard -k32,64,96 -p freq -t2 R1.fastq R2.fastq
I get freq_k32.hist, freq_k64.hist and freq_k96.hist files which is tab text files. How can I interpret the output files? How can I choose the optimal k-mer based on this *.hist files?

[freq_k32.hist.txt](https://github.com/bcgsc/ntCard/files/3991227/freq_k32.hist.txt)
[freq_k64.hist.txt](https://github.com/bcgsc/ntCard/files/3991228/freq_k64.hist.txt)
[freq_k96.hist.txt](https://github.com/bcgsc/ntCard/files/3991229/freq_k96.hist.txt)

**Comment by kmnip** [comment]
The histogram file has two columns: label in column 1 and count in column 2.
Line 1: `F1` is the number of k-mers in the reads.
Line 2: `F0` is the number of unique k-mers in the reads.
Lines 3 and onward report the k-mer count (coverage) histogram. For example, in your histogram for k32, there are 3,135,516,843 k-mers with count=1, 212,005,259 k-mers with count=2, etc.

**Comment by kmnip** [comment]
Usually, the "optimal" k-mer has the largest number of unique k-mers (eg. `F0`).
Among the 3 k-mer sizes, it looks like k64 was the "optimal" k-mer.

| k     | F0    |
| --- | --- |
| 32 | 4845247021 |
| 64 | 7068353342 |
| 96 | 6946441357 |

**Comment by hidvegin** [comment]
I understand it. Thank you for your answer, it was very helpful.
