### ISSUE TITLE
feature request: specify output prefix or name

### ISSUE THREAD

**Issue by rozovr** [bcgsc/ntCard#3]
Thanks for making ntCard, I think it's a great tool and will be very useful!

One small tweak I was hoping for is that outputs keep getting the same name, 'freq_kXX.hist'. Can you add a flag to allow this to specified by the user, so that one can keep track of histograms of several different files? Otherwise, I noticed a second binary is created in /bin - does it do something different?

Thanks again, and keep up the great work!
Cheers, R

**Comment by mohamadi** [comment]
@rozovr Hi Roye. Thank you so much for reporting this. I just added this feature to specify the prefix for output hist files. This works by passing `-p MYPREF` or `--pref=MYPREF`. Please let me know if you need other modifications.

Hamid

**Comment by rozovr** [comment]
Very cool, thanks!
