### ISSUE TITLE
Compilation blocked because of Werror

### ISSUE THREAD

**Issue by Malfoy** [bcgsc/ntCard#41]
Using gcc version 9.3.0 on Ubuntu
I got a compilation problem due to a warning that blocks the compilation because of -Werror

ntcard.cpp: In function ‘void stRead(const string&, const std::vector<unsigned int>&, uint16_t*, size_t*)’:
ntcard.cpp:166:35: error: type qualifiers ignored on cast result type [-Werror=ignored-qualifiers]
  166 |    ntComp((const uint64_t)(*itr)[0], t_Counter + k * opt::nSamp * opt::rBuck);

Without the -Werror flag I got
ntcard.cpp: In function ‘void stRead(const string&, const std::vector<unsigned int>&, uint16_t*, size_t*)’:
ntcard.cpp:166:35: warning: type qualifiers ignored on cast result type [-Wignored-qualifiers]
  166 |    ntComp((const uint64_t)(*itr)[0], t_Counter + k * opt::nSamp * opt::rBuck);

**Comment by jowong4** [comment]
Thanks for notifying us. This has been addressed in #43 . We will be making a new release very soon.
