### ISSUE TITLE
Problems w.r.t speed of ntCard and accuracy in genome size estimation

### ISSUE THREAD

**Issue by Souvadra** [bcgsc/ntCard#54]
I am trying to use ntCard to estimate the genome size on an Illumina paired ended 50x sequencing data distributed among 4 FASTQ files (each of size around 14 GB, making the total data approximately 56 GB). I have observed two problems while trying to do so: 

-  I used the command  ```ntCard -t4 -c3000000 -k21 -p freq @files.in``` for my experiment. It took around 40 minutes for ntCard to finish the simulation. This means in the ideal case it would have taken 40 * 4 / 16 = 10 minutes, had my data been divided among 16 files and used 16 threads. That doesn't match with the claim in the ntCard paper where it finished simulations of 500 GB data in 6 minutes. Am I doing anything wrong? Do I need to tune the parameters in some different way? I also used the default ```-c1000``` but it still took the same 40 minutes to finish the experiment. 

- I ran genomescope (after the necessary adjustments in the output file) on both the ```-c1000``` and ```-c3000000``` experiments to estimate the genome size. I got 2.5 Gbp and 2.8 Gbp as results (which is quite off from assembly distance 3.055 Gbp and exact histogram results 3.09 Gbp). I just wanted to confirm if I am supposed to expect the ntCard output to be slightly off like what I saw in my experiments. Or am I doing something wrong with the parameters during the ntCard simulations?

**Comment by vlad0x00** [comment]
Hi Souvadra,

Are your files perhaps compressed? I am not sure why it'd be slower than what was shown in the paper, but I'll look into it.

As for the second question, I think this is a limitation due to the size of the k-mer counters currently used in the code. I wanted to push an update to address that these days and I'll post an update here once it's done.

**Comment by Souvadra** [comment]
Thank you for your answers, 

The files I am using are **not** compressed. 

I will be waiting for your response and the update to your code for my second question.

**Comment by mohamadi** [comment]
- please provide the detailed cpu time, wall time using `/usr/bin/time -v`. it will provide system utilization. 
- what is your cluster/system architecture specification you're running ntcard on? It seems I/O is bottleneck and too slow on your computing environment. 
- maximum value for `c` is 65,535
- `k=21` is not  a good choice and is very small for human genome. Try using larger k values for estimation. you can also pass multiple k values, `k32,64,96`
- can you share your data somewhere so we can take a look?

**Comment by Souvadra** [comment]
1. Here are the detailed `/usr/bin/time --verbose` results of my simulation.
`Runtime(sec): 2441.9570`
    `Command being timed: "ntcard -t4 -c3000000 -k21 -p freq_full @lib.in"`
    `User time (seconds): 2499.79`
    `System time (seconds): 818.65`
    `Percent of CPU this job got: 135%`
    `Elapsed (wall clock) time (h:mm:ss or m:ss): 40:41.98`
    `Average shared text size (kbytes): 0`
    `Average unshared data size (kbytes): 0`
    `Average stack size (kbytes): 0`
    `Average total size (kbytes): 0`
    `Maximum resident set size (kbytes): 529824`
    `Average resident set size (kbytes): 0`
    `Major (requiring I/O) page faults: 5`
    `Minor (reclaiming a frame) page faults: 131718`
    `Voluntary context switches: 118135853`
    `Involuntary context switches: 3371`
    `Swaps: 0`
    `File system inputs: 1238`
    `File system outputs: 0`
    `Socket messages sent: 0`
    `Socket messages received: 0`
    `Signals delivered: 0`
    `Page size (bytes): 4096`
    `Exit status: 0`

2. The simulation was done on a dual-socket Intel Xeon Processor E5-2698 v3 processor with 32 cores. To be more precise, I am using this [supercomputer](https://docs.nersc.gov/systems/cori/). 

3. The input data I used: 
`human/Illumina/CHM13_pcrfree/SRR1997411_1.fastq`
`human/Illumina/CHM13_pcrfree/SRR1997411_2.fastq`
`human/Illumina/CHM13_pcrfree/SRR3189741_1.fastq`
`human/Illumina/CHM13_pcrfree/SRR3189741_2.fastq`

4. Thank you for your clarification w.r.t the maximum value of `c`. I need `k = 21` for my analysis. Hence I was using that particular value of `k`. Is there any reason why choosing lower values of `k` may affect ntCard performance?

**Comment by mohamadi** [comment]
- Yes, that's what I said. The CPU utilization is `135%` meaning you are utilizing slightly better than a single thread and passing `-t4` doesn't improve performance since your system I/O is too slow (most of the time is spent on I/O rather than computing). In the experiments we performed and reported in the ntCard paper on our cluster servers using `-t12` the CPU utilization was `~1140%` (almost utilizing all threads).
- The genome size estimation performance is related to genomescope not to ntCard and even if you use exact k-mer counting methods like KMC or DSK you could get similar results. What I meant was `k=21` may not be optimal `k` (usually the `k` value providing max distinct k-mers) for assembly and gnome size estimation.
- I'll take a look at those data you sent.

**Comment by Souvadra** [comment]
Thank you for your clarifications.

**Comment by mohamadi** [comment]
I downloaded the same sequencing data sets from NCBI:
```
$ cat lib.in 
SRR1997411_1.fastq
SRR1997411_2.fastq
SRR3189741_1.fastq
SRR3189741_2.fastq
```
 This is what I got by running ntCard on our server. Note the CPU utilization is `392%`.
```
$ /usr/bin/time -v ntcard -t4 -k21 -p freq_full @lib.in
Runtime(sec): 504.8966
	Command being timed: "ntcard -t4 -k21 -p freq_full @lib.in"
	User time (seconds): 1807.35
	System time (seconds): 172.82
	Percent of CPU this job got: 392%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 8:24.90
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 527708
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 3738206
	Voluntary context switches: 29
	Involuntary context switches: 603
	Swaps: 0
	File system inputs: 0
	File system outputs: 8
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0
```
I will take a look at genome size estimates if I get chance later.

**Comment by Souvadra** [comment]
Thank you again, @mohamadi, for your clarifications. Now, I understand what was going on in my simulations.
